"""empty message

Revision ID: 0e531f77d189
Revises: ffd4cb0aad8c
Create Date: 2023-10-23 19:30:50.740502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e531f77d189'
down_revision = 'ffd4cb0aad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_column('precio')

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('monto_neto', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('monto_bruto', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('monto_impuesto', sa.Double(), nullable=True))
        batch_op.drop_constraint('venta_ibfk_2', type_='foreignkey')
        batch_op.drop_column('folios_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('venta_ibfk_2', 'folios', ['folios_id'], ['id'])
        batch_op.drop_column('monto_impuesto')
        batch_op.drop_column('monto_bruto')
        batch_op.drop_column('monto_neto')
        batch_op.drop_column('folio')

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
