"""empty message

Revision ID: 316fd5547154
Revises: 7821adeb5de0
Create Date: 2023-06-19 23:46:09.976151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316fd5547154'
down_revision = '7821adeb5de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
