"""empty message

Revision ID: 624cf34f7ae4
Revises: 
Create Date: 2023-11-07 22:09:09.796500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624cf34f7ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rango_desde', sa.String(length=15), nullable=True),
    sa.Column('rango_hasta', sa.String(length=15), nullable=True),
    sa.Column('fecha_asignacion', sa.Date(), nullable=True),
    sa.Column('rsapk', sa.String(length=1000), nullable=True),
    sa.Column('frma', sa.String(length=1000), nullable=True),
    sa.Column('rsask', sa.String(length=1000), nullable=True),
    sa.Column('rsapubk', sa.String(length=1000), nullable=True),
    sa.Column('ultimo_utilizado', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('clave', sa.String(length=200), nullable=True),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_abono_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['tipo_abono_id'], ['tipo_abono.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('detalle', sa.String(length=30), nullable=True),
    sa.Column('precio', sa.Double(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('folio', sa.String(length=15), nullable=True),
    sa.Column('monto_neto', sa.Double(), nullable=True),
    sa.Column('monto_bruto', sa.Double(), nullable=True),
    sa.Column('monto_impuesto', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    op.drop_table('producto')
    op.drop_table('abono')
    op.drop_table('usuario')
    op.drop_table('tipo_abono')
    op.drop_table('material')
    op.drop_table('folios')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
