"""empty message

Revision ID: 659c994eb4f2
Revises: 4db85724c676
Create Date: 2023-11-27 21:14:40.172518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '659c994eb4f2'
down_revision = '4db85724c676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
