"""empty message

Revision ID: f19a7f333960
Revises: 316fd5547154
Create Date: 2023-06-21 21:01:55.096825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19a7f333960'
down_revision = '316fd5547154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_abono_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['tipo_abono_id'], ['tipo_abono.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('detalle', sa.String(length=30), nullable=True),
    sa.Column('precio', sa.String(length=30), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('folios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['folios_id'], ['folios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    op.drop_table('producto')
    op.drop_table('abono')
    op.drop_table('tipo_abono')
    op.drop_table('material')
    op.drop_table('folios')
    op.drop_table('categoria')
    # ### end Alembic commands ###
