"""empty message

Revision ID: ffd4cb0aad8c
Revises: 3097e3b8de34
Create Date: 2023-10-17 21:35:35.466769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd4cb0aad8c'
down_revision = '3097e3b8de34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_asignacion', sa.Date(), nullable=True))
        batch_op.drop_column('fecha_vencimiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DATE(), nullable=True))
        batch_op.drop_column('fecha_asignacion')

    # ### end Alembic commands ###
